### PR TITLE
using evstore for vdom compatibility

### PR DESCRIPTION
**Pull request by deepak1556**

### CODE REVIEW

**Comment by Raynos** [comment]
Yep. This is something I still need to do :)

Thanks!

**Comment by AutoSponge** [comment]
I loaded up @deepak1556 's example (browserified) in an IE8/Win7 VM and it worked when the appropriate shims were added.  :+1:

**Comment by kumavis** [comment]
Just ran into this. https://github.com/Raynos/mercury/issues/122

**Comment by kumavis** [comment]
@AutoSponge which shims? probly `isArray`, anything else?

**Comment by kumavis** [comment]
How can we resolve this implicit peer dependency? should vdom provide the delegator?

**Comment by Raynos** [comment]
@kumavis we just need to update dom-delegator.

**Comment by deepak1556** [comment]
@Raynos is there anything else i need to update on this PR ?

**Comment by Raynos** [comment]
@deepak1556 nope.

**Comment by Raynos** [comment]
Added @deepak1556 as a collaborator.

Published v13.0.0

**Comment by Raynos** [comment]
Published as v13.0.1 >_>;

**Comment by AutoSponge** [comment]
@kumavis I used the [cdn](https://cdn.polyfill.io/v1/polyfill.min.js)

**Comment by kumavis** [comment]
oh cool
> The polyfill service selectively bundles browser polyfills based on the User-Agent header supplied in a request, with the intention of allowing JavaScript and CSS developers to use modern standards in legacy user agents that do not natively support the standard. Think of it like a pair of glasses for your aging browser.

**Pull request merged**
